///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song02-2.aks
/// Generation time: domingo, 23 de octubre de 2016, 02:14:33 CEST
///

/// Song 'song02' metadata macros
#define song02_address  0x40
#define song02_size          529
#define song02_end      0x251

/// Song 'song02' array declaration
extern void song02[song02_size];
